---
- name: Pull image from repository
  docker_image:
    name: rohbikariuki/rohbikariuki/yolo-backend:v1.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: brian-yolo-backend
    image: rohbikariuki/rohbikariuki/yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes