---
- name: Ensure Docker network exists
  docker_network:
    name: app-net

- name: Pull backend image from Docker Hub
  docker_image:
    name: rohbikariuki/yolo-backend:v1.0.0
    source: pull

- name: Run backend container
  docker_container:
    name: brian-yolo-backend
    image: rohbikariuki/yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    restart_policy: always
  become: yes
