apiVersion: v1
kind: Namespace
metadata:
  name: yolo-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
  namespace: yolo-namespace
  labels:
    app: yolo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
      - name: yolo-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: yolo-namespace
spec:
  type: LoadBalancer
  selector:
    app: yolo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
